---
- name: Install Apache and PHP
  hosts: all
  vars:
    mysql_host: "{{ mysql_host }}"
    mysql_user: "bookstore_user"
    mysql_password: "S3cur3L0gin!"
  remote_user: ubuntu
  become: yes

  roles:
  - apache_php
