- name: Wait for SSH to be available
  ansible.builtin.wait_for:
    port: 22
    delay: 10
    timeout: 60

- name: Install Apache and PHP
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - apache2
      - php
      - php-mysql
      - libapache2-mod-php
    state: present

- name: Delete existing index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Clone PHP Bookstore Website Example from GitHub
  ansible.builtin.git:
    repo: https://github.com/blue-sky-dev/PHP-Bookstore-Website-Example.git
    dest: /var/www/html/
    force: true

- name: Make sure Apache can read the PHP Bookstore files
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: "0755"
    recurse: true

- name: Make sure Apache is running
  ansible.builtin.systemd:
    name: apache2
    state: started


- name: Update connectDB.php with new database host, user, and password
  ansible.builtin.replace:
    path: /var/www/html/bookstore/connectDB.php
    regexp: "mysql:host=.*?;port=3306;dbname=bookstore','.*?', '.*?'"
    replace: "mysql:host={{ mysql_host }};port=3306;dbname=bookstore','{{ apache_php_mysql_user }}', '{{ apache_php_mysql_password }}'"

- name: Update database connection details in PHP files
  ansible.builtin.shell: |
    sed -i \
    -e 's/book/Book/g' \
    -e 's/cart/Cart/g' \
    -e 's/Register.php/register.php/g' \
    -e 's/users/Users/g' \
    -e 's/order/Order/g' \
    -e 's/customer/Customer/g' \
    -e 's/Bookstore/bookstore/g' \
    -e 's/\$servername = ".*";/\$servername = "{{ mysql_host }}";/g' \
    -e 's/\$username = ".*";/\$username = "{{ apache_php_mysql_user }}";/g' \
    -e 's/\$password = ".*";/\$password = "{{ apache_php_mysql_password }}";/g' \
    {{ item }}
  loop:
    - /var/www/html/bookstore/index.php
    - /var/www/html/bookstore/register.php
    - /var/www/html/bookstore/edituser.php
    - /var/www/html/bookstore/checkout.php
  changed_when: false
