---

- name: Install MySQL Server and Python3-mysql
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: 
      - python3-pymysql
      - mysql-server  
    state: latest

- name: Start MySQL Service and enable on start
  service:
    name: mysql
    state: started
    enabled: yes


- name: Save root password in .my.cnf
  template:
    src: root_cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: '0600'


- name: Set password for root user
  mysql_user:
    name: "root"
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    host: 'localhost'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present


- name: Create MySQL User
  mysql_user:
    name: "bookstore_user"
    password: "S3cur3L0gin!"
    host: '%'
    priv: '*.*:ALL'
    state: present


- name: Create MySQL Database
  mysql_db:
    name: "bookstore"
    state: present


- name: Download SQL dump from GitHub
  get_url:
    url: "https://raw.githubusercontent.com/blue-sky-dev/PHP-Bookstore-Website-Example/main/bookstore/database.sql"
    dest: "/home/ubuntu/"

- name: Modify and remove first two lines from SQL dump file
  command: "sed -i '1,2d; s/`book`/Book/g' /home/ubuntu/database.sql"


- name: Update mysql.conf.d file
  ansible.builtin.command:
    cmd: >
      sed -i
      -e 's/mysqlx-bind-address\s*=\s*127\.0\.0\.1/mysqlx-bind-address     = 0.0.0.0/g'
      -e 's/bind-address\s*=\s*127\.0\.0\.1/bind-address            = 0.0.0.0/g'
      /etc/mysql/mysql.conf.d/mysqld.cnf
  Become: yes

- name: Restart MySQL Service
  service:
    name: mysql
    state: restarted
    
      
- name: Import SQL dump into MySQL database
  mysql_db:
    name: "bookstore"
    state: import
    target: "/home/ubuntu/database.sql"

