- name: Install MySQL Server and Python3-mysql
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - python3-pymysql
      - mysql-server
    state: present

- name: Start MySQL Service and enable on start
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Save root password in .my.cnf
  ansible.builtin.template:
    src: root_cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: '0600'


- name: Set password for root user
  community.mysql.mysql_user:
    name: "root"
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    host: 'localhost'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present


- name: Create MySQL User
  community.mysql.mysql_user:
    name: "{{ mysql_mysql_user }}"
    password: "{{ mysql_mysql_password }}"
    host: '%'
    priv: '*.*:ALL'
    state: present


- name: Create MySQL Database
  community.mysql.mysql_db:
    name: "bookstore"
    state: present


- name: Download SQL dump from GitHub
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/blue-sky-dev/PHP-Bookstore-Website-Example/main/bookstore/database.sql"
    dest: "/home/ubuntu/"
    mode: '0644'

- name: Modify and remove first two lines from SQL dump file
  ansible.builtin.command: "sed -i '1,2d; s/`book`/Book/g' /home/ubuntu/database.sql"
  changed_when: false

- name: Update mysql.conf.d file
  ansible.builtin.command:
    cmd: >
      sed -i
      -e 's/mysqlx-bind-address\s*=\s*127\.0\.0\.1/mysqlx-bind-address     = 0.0.0.0/g'
      -e 's/bind-address\s*=\s*127\.0\.0\.1/bind-address            = 0.0.0.0/g'
      /etc/mysql/mysql.conf.d/mysqld.cnf
  changed_when: false

- name: Restart MySQL Service
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Import SQL dump into MySQL database
  community.mysql.mysql_db:
    name: "bookstore"
    state: import
    target: "/home/ubuntu/database.sql"
